# theme.toml template for a Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for an example

name = "bs3theme"
license = "MIT"
licenselink = "https://github.com/awalker/bs3theme/blob/master/LICENSE.md"
description = ""
homepage = ""
tags = ["responsive", "bootstrap"]
features = ["responsive", ""]
min_version = 0.18

[author]
  name = "Adam Walker"
  homepage = "//github.com/awalker"
