# theme.toml template for a Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for an example

name = "HHtheme"
license = "MIT"
licenselink = "https://github.com/virtmindset/hhtheme/blob/master/LICENSE.md"
description = ""
homepage = "http://huddlehouse.com/"
tags = ["responsive", ""]
features = ["responsive", ""]
min_version = 0.18

[author]
  name = "Adam Walker"
  homepage = "//github.com/virtualmindset"
